### ISSUE TITLE
经纬度转墨卡托可否用于展开球面的计算

### ISSUE THREAD

**Issue by yaoweijiao** [wylloong/Geography_coordinate_transform_lite#1]
你好，想问下经纬度转磨卡托是否可以用于对球形表面展成平面的计算。还有20037508.34这个数值是什么，谢谢指教

**Comment by wylloong** [comment]
墨卡托坐标系是对标准圆的展开，具体可参考 [墨卡托投影原理](http://www.cnblogs.com/DHUtoBUAA/p/6706642.html)
